INSERT INTO categories (name, slug, icon, color) VALUES
  ('18+ Content', '18-plus', '🔞', '#dc2626'),
  ('Education', 'education', '📚', '#3b82f6'),
  ('Business', 'business', '💼', '#f59e0b'),
  ('Gaming', 'gaming', '🎮', '#8b5cf6'),
  ('Music', 'music', '🎵', '#ec4899'),
  ('Sports', 'sports', '⚽', '#10b981'),
  ('Technology', 'technology', '💻', '#6366f1'),
  ('Entertainment', 'entertainment', '🎬', '#f97316'),
  ('News', 'news', '📰', '#64748b'),
  ('Health', 'health', '🏥', '#ef4444'),
  ('Finance', 'finance', '💰', '#84cc16'),
  ('Travel', 'travel', '✈️', '#06b6d4'),
  ('Food', 'food', '🍕', '#f43f5e'),
  ('Fashion', 'fashion', '👗', '#d946ef'),
  ('Art', 'art', '🎨', '#a78bfa'),
  ('Science', 'science', '🔬', '#2563eb'),
  ('Religion', 'religion', '🙏', '#92400e'),
  ('Politics', 'politics', '🏛️', '#475569'),
  ('Crypto', 'crypto', '₿', '#f59e0b'),
  ('Movies', 'movies', '🎦', '#7c3aed'),
  ('Anime', 'anime', '🌸', '#e879f9'),
  ('Books', 'books', '📖', '#16a34a'),
  ('Photography', 'photography', '📸', '#0369a1'),
  ('Fitness', 'fitness', '💪', '#dc2626'),
  ('Cooking', 'cooking', '👨‍🍳', '#d97706'),
  ('Language', 'language', '🗣️', '#0891b2'),
  ('Programming', 'programming', '⌨️', '#7c3aed'),
  ('Investment', 'investment', '📈', '#16a34a'),
  ('Mental Health', 'mental-health', '🧠', '#6366f1'),
  ('Parenting', 'parenting', '👶', '#ec4899'),
  ('Pets', 'pets', '🐾', '#f59e0b'),
  ('Environment', 'environment', '🌿', '#16a34a'),
  ('Automotive', 'automotive', '🚗', '#64748b'),
  ('Real Estate', 'real-estate', '🏠', '#b45309'),
  ('Career', 'career', '🎯', '#0ea5e9'),
  ('Relationship', 'relationship', '❤️', '#e11d48'),
  ('Comedy', 'comedy', '😂', '#facc15'),
  ('History', 'history', '🏺', '#78350f'),
  ('Philosophy', 'philosophy', '💭', '#4b5563'),
  ('Spirituality', 'spirituality', '✨', '#8b5cf6'),
  ('DIY', 'diy', '🔧', '#92400e'),
  ('Marketing', 'marketing', '📣', '#c026d3'),
  ('Design', 'design', '🎭', '#7c3aed'),
  ('Legal', 'legal', '⚖️', '#475569'),
  ('Freelance', 'freelance', '💡', '#f59e0b'),
  ('Forex', 'forex', '💱', '#059669'),
  ('NFT', 'nft', '🖼️', '#8b5cf6'),
  ('Dating', 'dating', '💕', '#f43f5e'),
  ('Memes', 'memes', '🤣', '#facc15'),
  ('LGBTQ+', 'lgbtq', '🏳️‍🌈', '#ec4899'),
  ('Kids', 'kids', '🧒', '#60a5fa'),
  ('Seniors', 'seniors', '👴', '#9ca3af'),
  ('Expats', 'expats', '🌍', '#06b6d4'),
  ('Study Groups', 'study-groups', '📝', '#3b82f6'),
  ('Job Hunting', 'job-hunting', '🔍', '#f97316')
ON CONFLICT (slug) DO NOTHING;
