INSERT INTO countries (code, name, flag_emoji, continent, region) VALUES
  ('AF', 'Afghanistan', '🇦🇫', 'asia', 'Southern Asia'),
  ('AL', 'Albania', '🇦🇱', 'europe', 'Southern Europe'),
  ('DZ', 'Algeria', '🇩🇿', 'africa', 'Northern Africa'),
  ('AD', 'Andorra', '🇦🇩', 'europe', 'Southern Europe'),
  ('AO', 'Angola', '🇦🇴', 'africa', 'Sub-Saharan Africa'),
  ('AG', 'Antigua and Barbuda', '🇦🇬', 'north-america', 'Caribbean'),
  ('AR', 'Argentina', '🇦🇷', 'south-america', 'South America'),
  ('AM', 'Armenia', '🇦🇲', 'asia', 'Western Asia'),
  ('AU', 'Australia', '🇦🇺', 'oceania', 'Australia and New Zealand'),
  ('AT', 'Austria', '🇦🇹', 'europe', 'Western Europe'),
  ('AZ', 'Azerbaijan', '🇦🇿', 'asia', 'Western Asia'),
  ('BS', 'Bahamas', '🇧🇸', 'north-america', 'Caribbean'),
  ('BH', 'Bahrain', '🇧🇭', 'asia', 'Western Asia'),
  ('BD', 'Bangladesh', '🇧🇩', 'asia', 'Southern Asia'),
  ('BB', 'Barbados', '🇧🇧', 'north-america', 'Caribbean'),
  ('BY', 'Belarus', '🇧🇾', 'europe', 'Eastern Europe'),
  ('BE', 'Belgium', '🇧🇪', 'europe', 'Western Europe'),
  ('BZ', 'Belize', '🇧🇿', 'north-america', 'Central America'),
  ('BJ', 'Benin', '🇧🇯', 'africa', 'Sub-Saharan Africa'),
  ('BT', 'Bhutan', '🇧🇹', 'asia', 'Southern Asia'),
  ('BO', 'Bolivia', '🇧🇴', 'south-america', 'South America'),
  ('BA', 'Bosnia and Herzegovina', '🇧🇦', 'europe', 'Southern Europe'),
  ('BW', 'Botswana', '🇧🇼', 'africa', 'Sub-Saharan Africa'),
  ('BR', 'Brazil', '🇧🇷', 'south-america', 'South America'),
  ('BN', 'Brunei', '🇧🇳', 'asia', 'South-eastern Asia'),
  ('BG', 'Bulgaria', '🇧🇬', 'europe', 'Eastern Europe'),
  ('BF', 'Burkina Faso', '🇧🇫', 'africa', 'Sub-Saharan Africa'),
  ('BI', 'Burundi', '🇧🇮', 'africa', 'Sub-Saharan Africa'),
  ('CV', 'Cabo Verde', '🇨🇻', 'africa', 'Sub-Saharan Africa'),
  ('KH', 'Cambodia', '🇰🇭', 'asia', 'South-eastern Asia'),
  ('CM', 'Cameroon', '🇨🇲', 'africa', 'Sub-Saharan Africa'),
  ('CA', 'Canada', '🇨🇦', 'north-america', 'Northern America'),
  ('CF', 'Central African Republic', '🇨🇫', 'africa', 'Sub-Saharan Africa'),
  ('TD', 'Chad', '🇹🇩', 'africa', 'Sub-Saharan Africa'),
  ('CL', 'Chile', '🇨🇱', 'south-america', 'South America'),
  ('CN', 'China', '🇨🇳', 'asia', 'Eastern Asia'),
  ('CO', 'Colombia', '🇨🇴', 'south-america', 'South America'),
  ('KM', 'Comoros', '🇰🇲', 'africa', 'Sub-Saharan Africa'),
  ('CG', 'Congo', '🇨🇬', 'africa', 'Sub-Saharan Africa'),
  ('CD', 'Congo (DRC)', '🇨🇩', 'africa', 'Sub-Saharan Africa'),
  ('CR', 'Costa Rica', '🇨🇷', 'north-america', 'Central America'),
  ('HR', 'Croatia', '🇭🇷', 'europe', 'Southern Europe'),
  ('CU', 'Cuba', '🇨🇺', 'north-america', 'Caribbean'),
  ('CY', 'Cyprus', '🇨🇾', 'asia', 'Western Asia'),
  ('CZ', 'Czech Republic', '🇨🇿', 'europe', 'Eastern Europe'),
  ('DK', 'Denmark', '🇩🇰', 'europe', 'Northern Europe'),
  ('DJ', 'Djibouti', '🇩🇯', 'africa', 'Sub-Saharan Africa'),
  ('DM', 'Dominica', '🇩🇲', 'north-america', 'Caribbean'),
  ('DO', 'Dominican Republic', '🇩🇴', 'north-america', 'Caribbean'),
  ('EC', 'Ecuador', '🇪🇨', 'south-america', 'South America'),
  ('EG', 'Egypt', '🇪🇬', 'africa', 'Northern Africa'),
  ('SV', 'El Salvador', '🇸🇻', 'north-america', 'Central America'),
  ('GQ', 'Equatorial Guinea', '🇬🇶', 'africa', 'Sub-Saharan Africa'),
  ('ER', 'Eritrea', '🇪🇷', 'africa', 'Sub-Saharan Africa'),
  ('EE', 'Estonia', '🇪🇪', 'europe', 'Northern Europe'),
  ('SZ', 'Eswatini', '🇸🇿', 'africa', 'Sub-Saharan Africa'),
  ('ET', 'Ethiopia', '🇪🇹', 'africa', 'Sub-Saharan Africa'),
  ('FJ', 'Fiji', '🇫🇯', 'oceania', 'Melanesia'),
  ('FI', 'Finland', '🇫🇮', 'europe', 'Northern Europe'),
  ('FR', 'France', '🇫🇷', 'europe', 'Western Europe'),
  ('GA', 'Gabon', '🇬🇦', 'africa', 'Sub-Saharan Africa'),
  ('GM', 'Gambia', '🇬🇲', 'africa', 'Sub-Saharan Africa'),
  ('GE', 'Georgia', '🇬🇪', 'asia', 'Western Asia'),
  ('DE', 'Germany', '🇩🇪', 'europe', 'Western Europe'),
  ('GH', 'Ghana', '🇬🇭', 'africa', 'Sub-Saharan Africa'),
  ('GR', 'Greece', '🇬🇷', 'europe', 'Southern Europe'),
  ('GD', 'Grenada', '🇬🇩', 'north-america', 'Caribbean'),
  ('GT', 'Guatemala', '🇬🇹', 'north-america', 'Central America'),
  ('GN', 'Guinea', '🇬🇳', 'africa', 'Sub-Saharan Africa'),
  ('GW', 'Guinea-Bissau', '🇬🇼', 'africa', 'Sub-Saharan Africa'),
  ('GY', 'Guyana', '🇬🇾', 'south-america', 'South America'),
  ('HT', 'Haiti', '🇭🇹', 'north-america', 'Caribbean'),
  ('HN', 'Honduras', '🇭🇳', 'north-america', 'Central America'),
  ('HU', 'Hungary', '🇭🇺', 'europe', 'Eastern Europe'),
  ('IS', 'Iceland', '🇮🇸', 'europe', 'Northern Europe'),
  ('IN', 'India', '🇮🇳', 'asia', 'Southern Asia'),
  ('ID', 'Indonesia', '🇮🇩', 'asia', 'South-eastern Asia'),
  ('IR', 'Iran', '🇮🇷', 'asia', 'Southern Asia'),
  ('IQ', 'Iraq', '🇮🇶', 'asia', 'Western Asia'),
  ('IE', 'Ireland', '🇮🇪', 'europe', 'Northern Europe'),
  ('IL', 'Israel', '🇮🇱', 'asia', 'Western Asia'),
  ('IT', 'Italy', '🇮🇹', 'europe', 'Southern Europe'),
  ('JM', 'Jamaica', '🇯🇲', 'north-america', 'Caribbean'),
  ('JP', 'Japan', '🇯🇵', 'asia', 'Eastern Asia'),
  ('JO', 'Jordan', '🇯🇴', 'asia', 'Western Asia'),
  ('KZ', 'Kazakhstan', '🇰🇿', 'asia', 'Central Asia'),
  ('KE', 'Kenya', '🇰🇪', 'africa', 'Sub-Saharan Africa'),
  ('KI', 'Kiribati', '🇰🇮', 'oceania', 'Micronesia'),
  ('KW', 'Kuwait', '🇰🇼', 'asia', 'Western Asia'),
  ('KG', 'Kyrgyzstan', '🇰🇬', 'asia', 'Central Asia'),
  ('LA', 'Laos', '🇱🇦', 'asia', 'South-eastern Asia'),
  ('LV', 'Latvia', '🇱🇻', 'europe', 'Northern Europe'),
  ('LB', 'Lebanon', '🇱🇧', 'asia', 'Western Asia'),
  ('LS', 'Lesotho', '🇱🇸', 'africa', 'Sub-Saharan Africa'),
  ('LR', 'Liberia', '🇱🇷', 'africa', 'Sub-Saharan Africa'),
  ('LY', 'Libya', '🇱🇾', 'africa', 'Northern Africa'),
  ('LI', 'Liechtenstein', '🇱🇮', 'europe', 'Western Europe'),
  ('LT', 'Lithuania', '🇱🇹', 'europe', 'Northern Europe'),
  ('LU', 'Luxembourg', '🇱🇺', 'europe', 'Western Europe'),
  ('MG', 'Madagascar', '🇲🇬', 'africa', 'Sub-Saharan Africa'),
  ('MW', 'Malawi', '🇲🇼', 'africa', 'Sub-Saharan Africa'),
  ('MY', 'Malaysia', '🇲🇾', 'asia', 'South-eastern Asia'),
  ('MV', 'Maldives', '🇲🇻', 'asia', 'Southern Asia'),
  ('ML', 'Mali', '🇲🇱', 'africa', 'Sub-Saharan Africa'),
  ('MT', 'Malta', '🇲🇹', 'europe', 'Southern Europe'),
  ('MH', 'Marshall Islands', '🇲🇭', 'oceania', 'Micronesia'),
  ('MR', 'Mauritania', '🇲🇷', 'africa', 'Sub-Saharan Africa'),
  ('MU', 'Mauritius', '🇲🇺', 'africa', 'Sub-Saharan Africa'),
  ('MX', 'Mexico', '🇲🇽', 'north-america', 'Central America'),
  ('FM', 'Micronesia', '🇫🇲', 'oceania', 'Micronesia'),
  ('MD', 'Moldova', '🇲🇩', 'europe', 'Eastern Europe'),
  ('MC', 'Monaco', '🇲🇨', 'europe', 'Western Europe'),
  ('MN', 'Mongolia', '🇲🇳', 'asia', 'Eastern Asia'),
  ('ME', 'Montenegro', '🇲🇪', 'europe', 'Southern Europe'),
  ('MA', 'Morocco', '🇲🇦', 'africa', 'Northern Africa'),
  ('MZ', 'Mozambique', '🇲🇿', 'africa', 'Sub-Saharan Africa'),
  ('MM', 'Myanmar', '🇲🇲', 'asia', 'South-eastern Asia'),
  ('NA', 'Namibia', '🇳🇦', 'africa', 'Sub-Saharan Africa'),
  ('NR', 'Nauru', '🇳🇷', 'oceania', 'Micronesia'),
  ('NP', 'Nepal', '🇳🇵', 'asia', 'Southern Asia'),
  ('NL', 'Netherlands', '🇳🇱', 'europe', 'Western Europe'),
  ('NZ', 'New Zealand', '🇳🇿', 'oceania', 'Australia and New Zealand'),
  ('NI', 'Nicaragua', '🇳🇮', 'north-america', 'Central America'),
  ('NE', 'Niger', '🇳🇪', 'africa', 'Sub-Saharan Africa'),
  ('NG', 'Nigeria', '🇳🇬', 'africa', 'Sub-Saharan Africa'),
  ('MK', 'North Macedonia', '🇲🇰', 'europe', 'Southern Europe'),
  ('NO', 'Norway', '🇳🇴', 'europe', 'Northern Europe'),
  ('OM', 'Oman', '🇴🇲', 'asia', 'Western Asia'),
  ('PK', 'Pakistan', '🇵🇰', 'asia', 'Southern Asia'),
  ('PW', 'Palau', '🇵🇼', 'oceania', 'Micronesia'),
  ('PA', 'Panama', '🇵🇦', 'north-america', 'Central America'),
  ('PG', 'Papua New Guinea', '🇵🇬', 'oceania', 'Melanesia'),
  ('PY', 'Paraguay', '🇵🇾', 'south-america', 'South America'),
  ('PE', 'Peru', '🇵🇪', 'south-america', 'South America'),
  ('PH', 'Philippines', '🇵🇭', 'asia', 'South-eastern Asia'),
  ('PL', 'Poland', '🇵🇱', 'europe', 'Eastern Europe'),
  ('PT', 'Portugal', '🇵🇹', 'europe', 'Southern Europe'),
  ('QA', 'Qatar', '🇶🇦', 'asia', 'Western Asia'),
  ('RO', 'Romania', '🇷🇴', 'europe', 'Eastern Europe'),
  ('RU', 'Russia', '🇷🇺', 'europe', 'Eastern Europe'),
  ('RW', 'Rwanda', '🇷🇼', 'africa', 'Sub-Saharan Africa'),
  ('KN', 'Saint Kitts and Nevis', '🇰🇳', 'north-america', 'Caribbean'),
  ('LC', 'Saint Lucia', '🇱🇨', 'north-america', 'Caribbean'),
  ('VC', 'Saint Vincent and the Grenadines', '🇻🇨', 'north-america', 'Caribbean'),
  ('WS', 'Samoa', '🇼🇸', 'oceania', 'Polynesia'),
  ('SM', 'San Marino', '🇸🇲', 'europe', 'Southern Europe'),
  ('ST', 'Sao Tome and Principe', '🇸🇹', 'africa', 'Sub-Saharan Africa'),
  ('SA', 'Saudi Arabia', '🇸🇦', 'asia', 'Western Asia'),
  ('SN', 'Senegal', '🇸🇳', 'africa', 'Sub-Saharan Africa'),
  ('RS', 'Serbia', '🇷🇸', 'europe', 'Southern Europe'),
  ('SC', 'Seychelles', '🇸🇨', 'africa', 'Sub-Saharan Africa'),
  ('SL', 'Sierra Leone', '🇸🇱', 'africa', 'Sub-Saharan Africa'),
  ('SG', 'Singapore', '🇸🇬', 'asia', 'South-eastern Asia'),
  ('SK', 'Slovakia', '🇸🇰', 'europe', 'Eastern Europe'),
  ('SI', 'Slovenia', '🇸🇮', 'europe', 'Southern Europe'),
  ('SB', 'Solomon Islands', '🇸🇧', 'oceania', 'Melanesia'),
  ('SO', 'Somalia', '🇸🇴', 'africa', 'Sub-Saharan Africa'),
  ('ZA', 'South Africa', '🇿🇦', 'africa', 'Sub-Saharan Africa'),
  ('SS', 'South Sudan', '🇸🇸', 'africa', 'Sub-Saharan Africa'),
  ('ES', 'Spain', '🇪🇸', 'europe', 'Southern Europe'),
  ('LK', 'Sri Lanka', '🇱🇰', 'asia', 'Southern Asia'),
  ('SD', 'Sudan', '🇸🇩', 'africa', 'Northern Africa'),
  ('SR', 'Suriname', '🇸🇷', 'south-america', 'South America'),
  ('SE', 'Sweden', '🇸🇪', 'europe', 'Northern Europe'),
  ('CH', 'Switzerland', '🇨🇭', 'europe', 'Western Europe'),
  ('SY', 'Syria', '🇸🇾', 'asia', 'Western Asia'),
  ('TW', 'Taiwan', '🇹🇼', 'asia', 'Eastern Asia'),
  ('TJ', 'Tajikistan', '🇹🇯', 'asia', 'Central Asia'),
  ('TZ', 'Tanzania', '🇹🇿', 'africa', 'Sub-Saharan Africa'),
  ('TH', 'Thailand', '🇹🇭', 'asia', 'South-eastern Asia'),
  ('TL', 'Timor-Leste', '🇹🇱', 'asia', 'South-eastern Asia'),
  ('TG', 'Togo', '🇹🇬', 'africa', 'Sub-Saharan Africa'),
  ('TO', 'Tonga', '🇹🇴', 'oceania', 'Polynesia'),
  ('TT', 'Trinidad and Tobago', '🇹🇹', 'north-america', 'Caribbean'),
  ('TN', 'Tunisia', '🇹🇳', 'africa', 'Northern Africa'),
  ('TR', 'Turkey', '🇹🇷', 'asia', 'Western Asia'),
  ('TM', 'Turkmenistan', '🇹🇲', 'asia', 'Central Asia'),
  ('TV', 'Tuvalu', '🇹🇻', 'oceania', 'Polynesia'),
  ('UG', 'Uganda', '🇺🇬', 'africa', 'Sub-Saharan Africa'),
  ('UA', 'Ukraine', '🇺🇦', 'europe', 'Eastern Europe'),
  ('AE', 'United Arab Emirates', '🇦🇪', 'asia', 'Western Asia'),
  ('GB', 'United Kingdom', '🇬🇧', 'europe', 'Northern Europe'),
  ('US', 'United States', '🇺🇸', 'north-america', 'Northern America'),
  ('UY', 'Uruguay', '🇺🇾', 'south-america', 'South America'),
  ('UZ', 'Uzbekistan', '🇺🇿', 'asia', 'Central Asia'),
  ('VU', 'Vanuatu', '🇻🇺', 'oceania', 'Melanesia'),
  ('VE', 'Venezuela', '🇻🇪', 'south-america', 'South America'),
  ('VN', 'Vietnam', '🇻🇳', 'asia', 'South-eastern Asia'),
  ('YE', 'Yemen', '🇾🇪', 'asia', 'Western Asia'),
  ('ZM', 'Zambia', '🇿🇲', 'africa', 'Sub-Saharan Africa'),
  ('ZW', 'Zimbabwe', '🇿🇼', 'africa', 'Sub-Saharan Africa')
ON CONFLICT (code) DO NOTHING;
